name: Playwright Tests
on:
  push:
    branches: [ feat/DV-000, main ]
  pull_request:
    branches: [ feat/DV-000, main ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Debugging
        run: |
          echo "LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}"
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: PythonWithPlaywrightVEnv
        environment-file: Config/environment.yml
    - name: Activate Conda Environment and Run tests
      run: |
        conda init bash
        source "$(conda info --base)/etc/profile.d/conda.sh" && conda activate PythonWithPlaywrightVEnv
        playwright install
        python -m pytest
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-reports
        path: Report/